# configuration.yaml
application_port: 8080
database:
  host: '127.0.0.1'
  port: 5432
  username: 'postgres'
  password: 'password'
  database_name: 'newsletter'
base_url: 'localhost'
sender_email: 'test@gmail.com'
authorization_token: 'my-secret-token'
email_client:
  timeout_milliseconds: 10000
  authorization_token: 'token'
  base_url: 'http://localhost:5000'
  sender_email: 'test@gmail.com'
